#!/usr/bin/env ruby
require 'startandkonnect'
require 'optparse'

options = {
    :region => nil,
    :instance => []
}

op = OptionParser.new do |parser|

  parser.on("-r", "--region REGION", "[REQUIRED] Name of AWS Region") do |region|
    options[:region] = region
  end

  parser.on("-i", "--instance INSTANCE NAME", "[REQUIRED] EC2 Instance name") do |instance|
    options[:instance] = instance
  end

end
op.parse(ARGV)

unless options[:region] && options[:instance]
  puts "Required parameters missing"
  puts op
  exit 1
end

aws_client = Startandkonnect::AWS.new(options[:region])
res_instance = aws_client.search_instances(["#{options[:instance]}"])
puts aws_client.start_instance(res_instance.reservations.first.instances.first.instance_id)