#!/usr/bin/env ruby
require 'startandkonnect'
require 'optparse'

options = {
    :region => nil,
    :instance => [],
    :stop => false
}

op = OptionParser.new do |parser|

  parser.on("-r", "--region REGION", "[REQUIRED] Name of AWS Region") do |region|
    options[:region] = region
  end

  parser.on("-i", "--instance INSTANCE NAME", "[REQUIRED] EC2 Instance name") do |instance|
    options[:instance] = instance
  end

  parser.on("-s", "--stop", "Action to perform") do |stop|
    options[:stop] = true
  end

end
op.parse(ARGV)

unless options[:region] && options[:instance]
  puts "Required parameters missing"
  puts op
  exit 1
end

aws = Startandkonnect::AWS.new(options[:region])
res_instance = aws.search_instances(["#{options[:instance]}"])
if res_instance.reservations.any?
  puts aws.stop_instance(res_instance.reservations.first.instances.first.instance_id) if options[:stop]
  puts aws.start_instance(res_instance.reservations.first.instances.first.instance_id) unless options[:stop]
else
  puts "This instance does not exist"
end